# Common configuration for APM2 autopilot
#
# node:
startup_px4_usb_quirk: false

# sys_status & sys_time connection options
conn:
  heartbeat_rate: 1.0    # send hertbeat rate in Hertz
  heartbeat_mav_type: "ONBOARD_CONTROLLER"
  timeout: 10.0          # hertbeat timeout in seconds
  timesync_rate: 0.0    # TIMESYNC rate in Hertz (feature disabled if 0.0)
  system_time_rate: 1.0  # send system time to FCU rate in Hertz (disabled if 0.0)

# sys_status
sys:
  min_voltage: 17.0   # diagnostics min voltage
  disable_diag: false # disable all sys_status diagnostics, except heartbeat

# sys_time
time:
  time_ref_source: "fcu"  # time_reference source
  timesync_mode: MAVLINK
  timesync_avg_alpha: 0.6 # timesync averaging factor

# command
cmd:
  use_comp_id_system_control: false # quirk for some old FCUs

# local_position
local_position:
  frame_id: "map"
  tf:
    send: true
    frame_id: "odom"
    child_frame_id: "base_link"
    send_fcu: false

# setpoint_velocity
setpoint_velocity:
  mav_frame: BODY_NED

# distance_sensor
distance_sensor:
  bottom:
    id: 0
    frame_id: "bottom_psd"
    field_of_view: 0.5
    send_tf: false
  back:
    id: 1
    frame_id: "back_sonar"
    field_of_view: 0.5
